"""update address table

Revision ID: 012b25a5c4f5
Revises: 3f0bb18e5536
Create Date: 2022-06-26 19:25:51.369317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012b25a5c4f5'
down_revision = '3f0bb18e5536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
