"""update address table

Revision ID: 2a2e8e75d9e1
Revises: d8b533059ff5
Create Date: 2022-06-26 19:30:55.957581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2e8e75d9e1'
down_revision = 'd8b533059ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'address', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'address', type_='unique')
    # ### end Alembic commands ###
