"""update posts table

Revision ID: 3216df59c7d8
Revises: c57805a707c9
Create Date: 2022-06-27 00:37:44.558965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3216df59c7d8'
down_revision = 'c57805a707c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
