"""update address table

Revision ID: 3f0bb18e5536
Revises: 664ea6851728
Create Date: 2022-06-26 19:21:17.276287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f0bb18e5536'
down_revision = '664ea6851728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
