"""update posts table

Revision ID: 44d4c935efb1
Revises: cbbef74e3230
Create Date: 2022-06-27 00:15:52.267681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d4c935efb1'
down_revision = 'cbbef74e3230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
