"""update address table

Revision ID: 51152ee0cabe
Revises: 5add008c8438
Create Date: 2022-06-26 19:12:43.428013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51152ee0cabe'
down_revision = '5add008c8438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
