"""update posts table

Revision ID: 556160a770af
Revises: f432c15bf25e
Create Date: 2022-06-27 00:33:20.315212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556160a770af'
down_revision = 'f432c15bf25e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
