"""add address table

Revision ID: 5add008c8438
Revises: 88bd75e46c59
Create Date: 2022-06-26 19:06:54.235518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5add008c8438'
down_revision = '88bd75e46c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
