"""update address table

Revision ID: 664ea6851728
Revises: 51152ee0cabe
Create Date: 2022-06-26 19:13:38.281840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664ea6851728'
down_revision = '51152ee0cabe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
