"""update address table

Revision ID: 8bb10109e931
Revises: 2a2e8e75d9e1
Create Date: 2022-06-27 00:09:56.840677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb10109e931'
down_revision = '2a2e8e75d9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
