"""update posts table

Revision ID: c57805a707c9
Revises: 556160a770af
Create Date: 2022-06-27 00:37:28.606410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c57805a707c9'
down_revision = '556160a770af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
