"""update address table

Revision ID: d8b533059ff5
Revises: 012b25a5c4f5
Create Date: 2022-06-26 19:27:11.321633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b533059ff5'
down_revision = '012b25a5c4f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
