"""update posts table

Revision ID: df923e2c89fb
Revises: 0fbac32f489f
Create Date: 2022-06-27 00:32:17.526886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df923e2c89fb'
down_revision = '0fbac32f489f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
