"""add relationship

Revision ID: f011a1b9d9d2
Revises: 499454c23434
Create Date: 2022-06-26 18:43:36.790462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f011a1b9d9d2'
down_revision = '499454c23434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
