"""update posts table

Revision ID: f432c15bf25e
Revises: df923e2c89fb
Create Date: 2022-06-27 00:32:41.993193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f432c15bf25e'
down_revision = 'df923e2c89fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
